# Note: make sure to install the `ansible.posix` and `community.general` collections from ansible
# galaxy before running the playbook.
---
- hosts: all
  become: true
  vars:
    ansible_python_interpreter: auto_silent
    operator_username: "{{ lookup('env', 'VADE_USERNAME') | default('operator', true) }}"
    public_key_path: "{{ lookup('env', 'VADE_PUBLIC_KEY_PATH') }}"

  tasks:
    ############
    # User setup
    ############
    - name: Fail if VADE_PUBLIC_KEY_PATH is not set
      fail:
        msg: "VADE_PUBLIC_KEY_PATH environment variable is missing!"
      when: lookup('env', 'VADE_PUBLIC_KEY_PATH') == ''
    - name: Setup passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo'
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ operator_username }}"
        shell: /bin/bash
        state: present
        groups: sudo
        append: true
        create_home: true

    - name: Set authorized key for remote user
      ansible.posix.authorized_key:
        user: "{{ operator_username }}"
        state: present
        key: "{{ lookup('file', public_key_path) }}"

    - name: Disable password authentication for root
      lineinfile:
        path: /etc/ssh/sshd_config
        state: present
        regexp: '^#?PermitRootLogin'
        line: 'PermitRootLogin prohibit-password'

    ############################
    # Set up unattended upgrades
    ############################
    - name: Set up unattended upgrades
      apt:
        pkg:
          - unattended-upgrades
        state: latest
        update_cache: true

    ###########
    # Setup ufw
    ###########
    - name: Install ufw
      apt:
        pkg:
          - ufw
        state: latest
        update_cache: true

    - name: UFW - Allow SSH connections
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Allow HTTP connections
      community.general.ufw:
        rule: allow
        port: 80
        proto: tcp

    - name: UFW - Allow HTTPS connections
      community.general.ufw:
        rule: allow
        port: 443
        proto: tcp

    - name: UFW - Enable and deny by default
      community.general.ufw:
        state: enabled
        default: deny
