[artifacts]
path = "artifacts"

[network]
reserve-ports = 1

[systemd-unit.generated]
template = "application"
exec-start = "{{ APP_ACTIVE_ARTIFACTS_DIR }}/goatcounter serve -listen :{{ APP_PORT }}"

[caddyfile.generated]
template = "reverse-proxy"
domains = ["goats.example.com"]
