---
- name: Ensure Caddyfile globally uses `local_certs`
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: auto_silent
  tasks:
    - name: Ensure local_certs global block is at the top of Caddyfile
      ansible.builtin.blockinfile:
        path: /etc/caddy/Caddyfile
        insertbefore: BOF
        block: |
          {
              local_certs
          }
