[artifacts]
path = "artifacts"

[network]
reserve-ports = 1

[systemd-unit]
template = "builtin://application"
exec-start = "python3 {{ APP_ACTIVE_ARTIFACTS_DIR }}/main.py"

[caddyfile]
template = "builtin://reverse-proxy"
domains = ["python-site.example.com"]
