[artifacts]
path = "artifacts"

[caddyfile.template]
builtin = "reverse-proxy"
vars = {
  domains = ["python-site.example.com"]
}

[[systemd-unit]]
[systemd-unit.template]
builtin = "webapp.service"
vars = {
  exec_start = "python3 {{ vade.app.paths.artifacts }}/main.py",
  extra_env_vars = {
    "MY_ENV_VAR" = "42"
  }
}
