[artifacts]
path = "artifacts"

[caddyfile.template]
builtin = "reverse-proxy"
vars = {
  domains = ["guestbook.example.com"]
}

[[systemd-unit]]
[systemd-unit.template]
builtin = "webapp.service"
vars = {
  exec_start = "{{ vade.app.paths.artifacts }}/guestbook"
}
